version: "3"
volumes:
  data-postgres:
    driver: local
services:
  postgres:
    image: "timescale/timescaledb-ha:pg16"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
      POSTGRES_DB: "app"
    volumes:
      - data-postgres:/home/postgres/pgdata/data

  mailpit:
    image: "axllent/mailpit"
    ports:
      - "8025:8025"
      - "1025:1025"
