#:schema node_modules/wrangler/config-schema.json
name = "getlicensed"
compatibility_date = "2024-04-19"
pages_build_output_dir = "./dist"

[env.production]
vars = {  ENVIRONMENT = "production"}
#route = { pattern = "getlicensed.dev", custom_domain = true}