name: Main
on:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
      - run: pnpm run lint
